
nohup python -u RL/agent/low_level.py --buffer_size 1000000 --dataset 'MRMB' --lr 0.0001 --alpha 1 --subagent_hidden_size=64 --exp 'both_action_2_30s' --clf 'vol' --device 'cuda:0' --transcation_cost 0.0002 --action_mode both --action_size 2 --label label_1 --reward_no_action False >./logs/low_level/MRMB/vol_1_both_action_2_30s.log 2>&1 &
nohup python -u RL/agent/low_level.py --buffer_size 1000000 --dataset 'MRMB' --lr 0.0001 --alpha 1 --subagent_hidden_size=64 --exp 'both_action_2_30s' --clf 'vol' --device 'cuda:0' --transcation_cost 0.0002 --action_mode both --action_size 2 --label label_2 --reward_no_action False >./logs/low_level/MRMB/vol_2_both_action_2_30s.log 2>&1 &
nohup python -u RL/agent/low_level.py --buffer_size 1000000 --dataset 'MRMB' --lr 0.0001 --alpha 1 --subagent_hidden_size=64 --exp 'both_action_2_30s' --clf 'vol' --device 'cuda:0' --transcation_cost 0.0002 --action_mode both --action_size 2 --label label_3 --reward_no_action False >./logs/low_level/MRMB/vol_3_both_action_2_30s.log 2>&1 &

nohup python -u RL/agent/low_level.py --buffer_size 1000000 --dataset 'MRMB' --lr 0.0001 --alpha 1 --subagent_hidden_size=64 --exp 'both_action_2_30s' --clf 'slope' --device 'cuda:0' --transcation_cost 0.0002 --action_mode both --action_size 2 --label label_1 --reward_no_action False >./logs/low_level/MRMB/slope_1_both_action_2_30s.log 2>&1 &
nohup python -u RL/agent/low_level.py --buffer_size 1000000 --dataset 'MRMB' --lr 0.0001 --alpha 1 --subagent_hidden_size=64 --exp 'both_action_2_30s' --clf 'slope' --device 'cuda:0' --transcation_cost 0.0002 --action_mode both --action_size 2 --label label_2 --reward_no_action False >./logs/low_level/MRMB/slope_2_both_action_2_30s.log 2>&1 &
nohup python -u RL/agent/low_level.py --buffer_size 1000000 --dataset 'MRMB' --lr 0.0001 --alpha 1 --subagent_hidden_size=64 --exp 'both_action_2_30s' --clf 'slope' --device 'cuda:0' --transcation_cost 0.0002 --action_mode both --action_size 2 --label label_3 --reward_no_action False >./logs/low_level/MRMB/slope_3_both_action_2_30s.log 2>&1 &


nohup python -u RL/agent/low_level.py --buffer_size 1000000 --dataset 'MRMB' --lr 0.0001 --alpha 1 --subagent_hidden_size=64 --exp 'both_action_5_30s' --clf 'vol' --device 'cuda:0' --transcation_cost 0.0005 --action_mode both --action_size 2 --label label_1 --reward_no_action False >./logs/low_level/MRMB/vol_1_both_action_5_30s.log 2>&1 &
nohup python -u RL/agent/low_level.py --buffer_size 1000000 --dataset 'MRMB' --lr 0.0001 --alpha 1 --subagent_hidden_size=64 --exp 'both_action_5_30s' --clf 'vol' --device 'cuda:0' --transcation_cost 0.0005 --action_mode both --action_size 2 --label label_2 --reward_no_action False >./logs/low_level/MRMB/vol_2_both_action_5_30s.log 2>&1 &
nohup python -u RL/agent/low_level.py --buffer_size 1000000 --dataset 'MRMB' --lr 0.0001 --alpha 1 --subagent_hidden_size=64 --exp 'both_action_5_30s' --clf 'vol' --device 'cuda:0' --transcation_cost 0.0005 --action_mode both --action_size 2 --label label_3 --reward_no_action False >./logs/low_level/MRMB/vol_3_both_action_5_30s.log 2>&1 &

nohup python -u RL/agent/low_level.py --buffer_size 1000000 --dataset 'MRMB' --lr 0.0001 --alpha 1 --subagent_hidden_size=64 --exp 'both_action_5_30s' --clf 'slope' --device 'cuda:0' --transcation_cost 0.0005 --action_mode both --action_size 2 --label label_1 --reward_no_action False >./logs/low_level/MRMB/slope_1_both_action_5_30s.log 2>&1 &
nohup python -u RL/agent/low_level.py --buffer_size 1000000 --dataset 'MRMB' --lr 0.0001 --alpha 1 --subagent_hidden_size=64 --exp 'both_action_5_30s' --clf 'slope' --device 'cuda:0' --transcation_cost 0.0005 --action_mode both --action_size 2 --label label_2 --reward_no_action False >./logs/low_level/MRMB/slope_2_both_action_5_30s.log 2>&1 &
nohup python -u RL/agent/low_level.py --buffer_size 1000000 --dataset 'MRMB' --lr 0.0001 --alpha 1 --subagent_hidden_size=64 --exp 'both_action_5_30s' --clf 'slope' --device 'cuda:0' --transcation_cost 0.0005 --action_mode both --action_size 2 --label label_3 --reward_no_action False >./logs/low_level/MRMB/slope_3_both_action_5_30s.log 2>&1 &

